apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mpo-example-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: mpo-example-app
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: harbor.sl.zone/mpo-example-app/helm
    targetRevision: 0.2.0
    chart: mpo-example-app
    helm:
      valuesObject:
        redisImage: harbor.sl.zone/mpo-example-app/redis
        backendImage: harbor.sl.zone/mpo-example-app/backend:0.2.0
        frontendImage:  harbor.sl.zone/mpo-example-app/frontend:0.2.0
        frontendHost: mpo-example-app.mpo.sikademo.com
        sluImage: harbor.sl.zone/mpo-example-app/slu:v0.85.0
        licenseKeySecretName: license
        imagePullSecretName: imagepullsecret
        redisPasswordSecretName: redis-password

