apiVersion: v1
kind: Secret
metadata:
  name: creds-repo-mpo-example-app
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
type: Opaque
stringData:
  password: bDcB_PoB8_Q5RW_ix4C
  url: harbor.sl.zone
  username: robot$mpo-example-app
