apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: counter
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: counter
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  source:
    repoURL: https://github.com/sika-training-examples/2025-11-04_akcenta_counter_example.git
    path: .
