apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    path: apps/lab0
    repoURL: https://github.com/ondrejsika/argocd-apps-public.git
    directory:
      recurse: true
      exclude: '{**/manifests/**,**/Chart.yaml,**/templates/**,**/values.yaml,**/values.*.yaml}'
