apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: egd-counter
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: egd-counter
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/sika-training-examples/2026-02-05_counter_egd_helm_example.git
    path: .
    helm:
      valuesObject:
        host: egd-counter.apps.training.germanywestcentral.aroapp.io
        hostExp: egd-counter-exp.apps.training.germanywestcentral.aroapp.io

        EXTRA_TEXT: 'EGD'
        FONT_COLOR: red
        BACKGROUND_COLOR: yellow

        backendReplicas: 2
        frontendReplicas: 2
        frontendExpReplicas: 2

        ingressTlsEnabled: false

        enableArgoCDHooks: true
        enableServiceMonitor: true
        openshiftDashboardEnabled: true
        openshiftConsoleLinkEnabled: true
        grafanaDashboardEnabled: true
