apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  url: https://argocd.k8s.sikademo.com
  admin.enabled: "true"
  application.instanceLabelKey: argocd.argoproj.io/instance
  exec.enabled: "true"
  oidc.config: |
    name: SSO
    issuer: https://sso.k8s.sikademo.com/realms/sikademo
    clientID: argocd
    clientSecret: argocd
    requestedScopes: ["openid", "profile", "email", "groups"]
    logoutURL: "https://sso.k8s.sikademo.com/realms/sikademo/protocol/openid-connect/logout?client_id=argocd&id_token_hint={{token}}&post_logout_redirect_uri=https://argocd.k8s.sikademo.com"
  oidc.tls.insecure.skip.verify: "true"
  server.rbac.log.enforce.enable: "false"
  timeout.hard.reconciliation: 0s
  timeout.reconciliation: 180s
