apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: counter
  namespace: counter
spec:
  promotionPolicies:
    - stageSelector:
        name: dev
      autoPromotionEnabled: true
