apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: dela-instagram
spec:
  applicationMenu:
    imageURL: https://raw.githubusercontent.com/ondrejsika/openshift-training/refs/heads/master/images/dela_icon_instagram_openshift.jpg
    section: Doggos
  href: https://instagram.com/jsemdela
  location: ApplicationMenu
  text: "@jsemdela (instagram)"
