apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headlamp
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://kubernetes-sigs.github.io/headlamp
    chart: headlamp
    targetRevision: 0.30.1
    helm:
      valuesObject:
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt
          hosts:
            - host: headlamp.loki.sikademo.com
              paths:
                - path: /
                  type: ImplementationSpecific
          tls:
            - secretName: headlamp.loki.sikademo.com-tls
              hosts:
                - headlamp.loki.sikademo.com
