apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: counter-gpe
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: example-counter-gpe
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
  - repoURL: https://helm.sikademo.com
    targetRevision: 0.2.2
    chart: counter-gpe
    helm:
      valueFiles:
      - $values/values/counter_gpe.values.yml
  - repoURL: 'https://github.com/ondrejsika/argocd-apps-public.git'
    ref: values
