apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: counter
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: examples
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://raw.githubusercontent.com/ondrejsika/helm-repo-sikademo/master/repo
    targetRevision: 2023.11.14
    chart: counter
    helm:
      releaseName: counter
      values: |
        host: countere.panda.k8s.sl.zone
        replicas: 1
