apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: counter-gpe
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: example-counter-gpe
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://helm.sikademo.com
    targetRevision: 0.2.2
    chart: counter-gpe
    helm:
      valuesObject:
        host: counter-gpe.panda.k8s.sl.zone
        ingressClassName: nginx
        backendReplicas: 10
