apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-o2
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: example
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/sikalabs/charts.git
    targetRevision: HEAD
    path: charts/hello-world
    helm:
      releaseName: example-o2
      values: |
        host: hello-o2.panda.k8s.sl.zone
        image: sikalabs/hello-world-server
        replicas: 1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
