apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: public-example-fingood
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: public-www
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/sikalabs/charts.git
    targetRevision: HEAD
    path: charts/hello-world
    helm:
      releaseName: hello-world-fingood
      values: |
        host: fingood.panda.k8s.oxs.cz
        image: sikalabs/hello-world-server:fingood
        replicas: 2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
