apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-from-helm-repo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: examples
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://helm.sikalabs.io
    targetRevision: 0.6.0
    chart: hello-world
    helm:
      releaseName: example-from-helm-repo
      values: |
        host: example-from-helm-repo.panda.k8s.sl.zone
        image: sikalabs/hello-world-server:v0.6.0
        TEXT: "Example from Helm repo"
