apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-webwings-foo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: examples
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/sikalabs/charts.git
    targetRevision: HEAD
    path: charts/hello-world
    helm:
      releaseName: example-webwings-foo
      values: |
        host: ww-foo.panda.k8s.sl.zone
        image: sikalabs/hello-world-server:ondrejsika
        TEXT: WW FOO
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
