apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-webwings-bar
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: examples
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/sikalabs/charts.git
    targetRevision: HEAD
    path: charts/hello-world
    helm:
      releaseName: example-webwings-bar
      values: |
        host: ww-bar.panda.k8s.sl.zone
        TEXT: WW BAR
        replicas: 3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
