apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-vault
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: example-vault
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: 0.20.1
    helm:
      releaseName: example-vault
      values: |
        # https://github.com/hashicorp/vault-helm/blob/main/values.yaml
        global:
          tlsDisable: true
        injector:
          enabled: false
        server:
          ingress:
            enabled: true
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt
            ingressClassName: nginx
            pathType: Prefix
            tls:
            - secretName: example-vault
              hosts:
                - example-vault.panda.k8s.sl.zone
            hosts:
            - host: example-vault.panda.k8s.sl.zone
              paths:
                - /
          dataStorage:
            enabled: true
            size: 1Gi
          ha:
            enabled: true
            replicas: 3
            raft:
              enabled: true

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
