apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-hello-eon
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: examples
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  source:
    repoURL: https://helm.sikademo.com
    targetRevision: 2023.10.23
    chart: counter-eon
    helm:
      releaseName: hello-eon
      values: |
        host: hello-eon.panda.k8s.oxs.cz
        replicas: 10
