apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-elm-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: example-elm
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://example-elm-helm-repo.vercel.app
    chart: example-elm-app
    targetRevision: 0.3.0
    helm:
      values: |
        host: example-elm-app.panda.k8s.sl.zone

