apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-ica-okd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: example-hello-ica-okd
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/sikalabs/charts.git
    path: charts/one-image
    helm:
      valuesObject:
        host: hello-ica-okd.panda.k8s.sl.zone
        image: ondrejsika/training-example-okd
        containerPort: 8000
