apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-ceps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: examples
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/sikalabs/charts.git
    targetRevision: HEAD
    path: charts/hello-world
    helm:
      releaseName: example-hello-ceps
      valuesObject:
        host: hello-ceps.panda.k8s.sl.zone
        image: sikalabs/hello-world-server:ceps
        replicas: 3
