apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hlidac
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: public-www
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/sikalabs/charts.git
    targetRevision: HEAD
    path: charts/hello-world
    helm:
      releaseName: hlidac
      values: |
        host: hlidac.panda.k8s.oxs.cz
        TEXT: Hlidac
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
