apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microcomp-example
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: examples
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/sikalabs/charts.git
    targetRevision: HEAD
    path: charts/hello-world
    helm:
      releaseName: microcomp-example
      values: |
        host: microcomp-example.panda.k8s.sl.zone
        image: sikalabs/hello-world-server:v0.6.0
        TEXT: "Hello from Microcomp"
