apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pss-counter-example
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: examples
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://raw.githubusercontent.com/ondrejsika/helm-repo-sikademo/master/repo/
    targetRevision: 2023.06.27
    chart: counter
    helm:
      releaseName: pss-counter-example
      values: |
        host: pss-counter-example.panda.k8s.sl.zone
