apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sikademo-com
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: sikademo-com
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/sikalabs/charts.git
    path: charts/one-image
    helm:
      valuesObject:
        host: sikademo.com
        image: ghcr.io/ondrejsika/sikademo.com
