apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: skaffold-example
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: skaffold-example
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/sikalabs/charts.git
    path: charts/one-image
    helm:
      valuesObject:
        host: skaffold-example.panda.k8s.sl.zone
        image: nginx
