apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: training-example-v0
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: examples
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  source:
    repoURL: https://github.com/sikalabs/charts.git
    targetRevision: HEAD
    path: charts/one-image
    helm:
      valuesObject:
        host: training-example-v0.panda.k8s.sl.zone
        image: ghcr.io/ondrejsika/training-example:v0
