apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: signpost
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: signpost
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  source:
    repoURL: https://github.com/sikalabs/charts.git
    path: charts/signpost
    helm:
      valuesObject:
        host: signpost.yetanothercorp.com
        signpost_yaml:
          SiteHeading: YetAnotherCorp Signpost
          CompanyName: YetAnotherCorp
          CompanyDomain: yetanothercorp.com
          CompanyUrl: https://yetanothercorp.com
          Rows:
            - Cols:
              - Blocks:
                - Heading: Global
                  Links:
                  - Title: Gitlab
                    URL: https://gitlab.yetanothercorp.com
                  - Title: Proxmox (direct)
                    URL: https://pve-1.yac.zone:8006
              - Blocks:
                - Heading: Prod Environment
                  Links:
                  - Title: ArgoCD Prod
                    URL: https://argocd.apps.prod.yac.zone
              - Blocks:
                - Heading: Dev Environment
                  Links:
                  - Title: ArgoCD Dev
                    URL: https://argocd.apps.dev.yac.zone
            - Cols:
              - Blocks: []
              - Blocks:
                - Heading: Prod Apps
                  Links:
                  - Title: yetanothercorp.com (site)
                    URL: https://yetanothercorp.com
                  - Title: Signpost
                    URL: https://signpost.yetanothercorp.com
              - Blocks:
                - Heading: Dev Apps
                  Links:
                  - Title: Hello YAC
                    URL: https://hello-yac.yac.dev
