apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: meta-joh-public
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: meta/joh
    repoURL: https://github.com/ondrejsika/argocd-apps-public.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
