apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-generali-from-package
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: hello-generali
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://helm.sikalabs.io
    chart: hello-world
    targetRevision: 0.10.0
    helm:
      valuesObject:
        host: hello-generali-from-package.k8s.sikademo.com
        image: sikalabs/hello-world-server:generali
        replicas: 3
