apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: counter-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: examples
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/ondrejsika/counter.git
    path: charts/counter
    helm:
      values: |
        host: counter.joh.k8s.sl.zone
