apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-o2
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: example
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  source:
    repoURL: https://github.com/sikalabs/charts.git
    targetRevision: HEAD
    path: charts/one-image
    helm:
      releaseName: hello-o2
      values: |
        host: hello-o2.joh.k8s.sl.zone
        image: ondrejsika/training-example-o2
