apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-uptime-kuma-jozef
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: example-uptime-kuma-jozef
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  source:
    repoURL: https://github.com/sikalabs/charts.git
    targetRevision: HEAD
    path: charts/uptime-kuma
    helm:
      releaseName: uptime-kuma-ogilvy
      values: |
        host: example-uptime-kuma-jozef.joh.k8s.sl.zone
