apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iceland-2
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: examples
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/sikalabs/charts.git
    targetRevision: generali
    path: charts/one-image
    helm:
      values: |
        host: iceland-2.joh.k8s.sl.zone
        image: ondrejsika/iceland-4
