apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: public-example-daktela
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: public-www
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/sikalabs/charts.git
    targetRevision: HEAD
    path: charts/hello-world
    helm:
      releaseName: hello-world-daktela
      values: |
        host: daktela.panda.k8s.oxs.cz
        image: sikalabs/hello-world-server:v0.6.0
        replicas: 2
        TEXT: Hello Daktela!
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
