apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: counter-manifests
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: counter-manifests
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/sika-training-examples/2024-06-26_counter-manifests.git
    path: .
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: frontend
      namespace: counter-manifests
      jsonPointers:
        - /spec/replicas
    - group: apps
      kind: Deployment
      name: backend
      namespace: counter-manifests
      jsonPointers:
        - /spec/replicas
