apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-k3s
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: hello-k3s
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/sikalabs/charts.git
    path: charts/hello-world
    helm:
      valuesObject:
        TEXT: "Hello K3s!"
        host: hello.k3s-mgmt.sikademo.com
        replicas: 3
