apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: counter
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
  syncWindows:
  - applications:
    - '*'
    duration: 10m
    kind: allow
    schedule: 0 * * * *
    timeZone: UTC
    manualSync: false
    # manualSync: true
