apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-kafdrop
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: kafka-kafdrop
  destination:
    namespace: kafka
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://github.com/sikalabs/charts.git
      path: charts/simple-kafdrop
      helm:
        valuesObject:
          # https://github.com/sikalabs/charts/blob/master/charts/simple-kafdrop/values.yaml
          host: kafka-kafdrop.apps.training.germanywestcentral.aroapp.io
          kafkaBootstrapServer: kafka-kafka-bootstrap.kafka.svc:9092
          ingressClassName: openshift-default
          tls: false
          ingressExtraAnnotations:
            route.openshift.io/termination: edge
            route.openshift.io/insecureEdgeTerminationPolicy: Redirect
    - repoURL: https://github.com/ondrejsika/argocd-apps-public.git
      path: ./clusters/openshift_training/kafka_kafdrop/manifests
