apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: counter
  namespace: counter
spec:
  interval: 1m0s
  subscriptions:
    - image:
        repoURL: ttl.sh/ondrejsika/kcd2026-kargo-example/backend
        allowTags: "^v[0-9]+"
        imageSelectionStrategy: NewestBuild
        discoveryLimit: 5
    - image:
        repoURL: ttl.sh/ondrejsika/kcd2026-kargo-example/fronend
        allowTags: "^v[0-9]+"
        imageSelectionStrategy: NewestBuild
        discoveryLimit: 5
    - git:
        repoURL: git@github.com:ondrejsika/kcd2026-kargo-example.git
        branch: master
        includePaths:
          - clusters/kcd/counter/values/dev/common.values.yaml
