apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: system
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      targetRevision: 8.5.10
      helm:
        valueFiles:
          - $values/apps/example_rke2/_system/argocd/argocd.values.yaml
    - repoURL: https://github.com/ondrejsika/argocd-apps-public.git
      ref: values
    - repoURL: https://github.com/ondrejsika/argocd-apps-public.git
      path: ./apps/example_lab0/_system/argocd/manifests
