apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: my-argocd-exec
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: my-argocd-exec
subjects:
  - kind: ServiceAccount
    name: argocd-server
    namespace: argocd
