apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: counter2
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: examples
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  source:
    repoURL: https://gitlab.sikalabs.com/examples/pss-sk/counter.git
    targetRevision: master
    path: .
    helm:
      releaseName: counter2
      values: |
        host: counter2.apps.slkp.uk
