apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-95"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: system
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  sources:
    - repoURL: https://github.com/argoproj-labs/argocd-image-updater.git
      targetRevision: stable
      path: ./manifests
    - repoURL: https://github.com/ondrejsika/argocd-apps-public.git
      path: ./apps/openshift/_system/argocd_image_updater/manifests
