apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: pg-backup-scheduled
  namespace: cnpg-example
spec:
  schedule: "0 0 2 * * *"
  backupOwnerReference: self
  method: barmanObjectStore
  cluster:
    name: pg
  immediate: true
