apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-scalable
  namespace: argocd
  annotations:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: loki-scalable
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: loki
      targetRevision: 6.37.0
      helm:
        valueFiles:
          - $values/apps/loki/loki_scalable/loki_scalable.values.yaml
    - repoURL: https://github.com/ondrejsika/argocd-apps-public.git
      ref: values
