apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: counter-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: counter
  destination:
    namespace: counter-prod
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/sika-training-examples/2025-10-10_asseco-example.git
    path: ./asseco-example-subchart
    helm:
      valueFiles:
        - ./values.yaml
        - ./values_prod.yaml
