apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: signpost
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: signpost
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  source:
    repoURL: https://github.com/sikalabs/charts.git
    path: charts/signpost
    helm:
      valuesObject:
        host: signpost.apps.akc.germanywestcentral.aroapp.io
        ingressClassName: openshift-default
        ingressTlsDisable: true
        ingressExtraAnnotations:
          route.openshift.io/termination: edge
          route.openshift.io/insecureEdgeTerminationPolicy: Redirect
        signpost_yaml:
          SiteHeading: OpenShift Signpost
          CompanyName: Ondrej Sika Training
          CompanyDomain: sika.io
          CompanyURL: https://sika.io
          Rows:
          - Cols:
            - Blocks:
              - Heading: OpenShift Platform
                Links:
                - Title: Console
                  URL: https://console-openshift-console.apps.akc.germanywestcentral.aroapp.io
                - Title: ArgoCD
                  URL: https://openshift-gitops-server-openshift-gitops.apps.akc.germanywestcentral.aroapp.io
            - Blocks:
              - Heading: Apps
                Links:
                - Title: Hello World
                  URL: https://hello-world.apps.akc.germanywestcentral.aroapp.io
