apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: www-counter-daktela
  namespace: argocd
spec:
  destination:
    namespace: www
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://helm.sikademo.com
    chart: counter
    targetRevision: 2022.12.20
    helm:
      releaseName: counter-daktela
      values: |
        host: counter-daktela.k8s.sikademo.com
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
