apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: www-hello-animato-stg
  namespace: argocd
spec:
  destination:
    namespace: www
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/sikalabs/charts.git
    targetRevision: HEAD
    path: charts/hello-world
    helm:
      releaseName: hello-animato-stg
      values: |
        host: hello-animato-stg.k8s.sikademo.com
        image: sikalabs/hello-world-server:animato-stg
        TEXT: '[STG] Hello Animato (staging)!'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
