apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: signpost
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: signpost
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  source:
    repoURL: https://github.com/sikalabs/charts.git
    path: charts/signpost
    helm:
      valuesObject:
        host: signpost.rke2.sikalabs.com
        signpost_yaml:
          SiteHeading: rke2
          CompanyName: Training
          CompanyDomain: sika.io
          CompanyURL: https://sika.io
          Rows:
          - Cols:
            - Blocks:
              - Heading: Platform
                Links:
                - Title: ArgoCD
                  URL: https://argocd.rke2.sikalabs.com
            - Blocks:
              - Heading: Apps
                Links:
                - Title: Hello World
                  URL: https://hello-world.rke2.sikademo.com
