apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: postgresql
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: hthttps://charts.bitnami.com/bitnami
    targetRevision: 14.3.1
    chart: postgresql
    helm:
      releaseName: example-from-helm-repo
      valuesObject:
      valuesObject:
