apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-hello-gpe
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: ondrej
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://helm.sikademo.com
    targetRevision: 0.2.0
    chart: simple-hello-gpe
    helm:
      valuesObject:
        image: registry.sikalabs.com/demo/2024-06-18-hello-gpe-image:v0.3.0
