apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: image-updater-example
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: image-updater-example
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/sikalabs/charts.git
    path: charts/hello-world
    helm:
      valuesObject:
        host: image-updater-example.k8s.sikademo.com
        image: ttl.sh/image-updater-example
        replicas: 2
