apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: astratex-counter-frontend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: astratex-counter
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/ondrejsika/counter.git
    path: charts/counter
    helm:
      valuesObject:
        API_ORIGIN: http://astratex-counter-backend-counter
        host: astratex-counter-frontend.k8s.sikademo.com
        replicas: 4
