apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: counter-from-git
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: examples
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/sika-training-examples/2023-11-23_counter_helm_chart.git
    targetRevision: HEAD
    path: .
    helm:
      releaseName: counter-from-git
      values: |
        host: counter-from-git.k8s.sikademo.com
