apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: counter-from-package
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: counter
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://helm.sikademo.com
    chart: counter
    targetRevision: 2023.11.23
    helm:
      releaseName: counter-from-package
      values: |
        host: counter-from-package.k8s.sikademo.com
        counterReplicas: 10
