apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: counter
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: counter
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://gitlab.sikademo.com/ondrejsika/cra-demo.git
    targetRevision: HEAD
    path: .
    helm:
      releaseName: counter
      values: |
        host: counter.k8s.sikademo.com
        replicas: 80
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
