apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-hello-world-public
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: examples
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  source:
    repoURL: https://github.com/sikalabs/charts.git
    targetRevision: HEAD
    path: charts/hello-world
    helm:
      releaseName: hello-world-public
      values: |
        host: hello-world.k8s.sikademo.com
        image: sikalabs/hello-world-server:ondrejsika
