apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-vaultwarden-o2
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: example-vaultwarden-o2
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  source:
    repoURL: https://github.com/sikalabs/charts.git
    targetRevision: HEAD
    path: charts/vaultwarden
    helm:
      releaseName: example-vaultwarden-o2
      values: |
        # https://github.com/sikalabs/charts/blob/master/charts/vaultwarden/values.yaml
        host: example-vaultwarden-o2.k8s.sikademo.com
        ADMIN_TOKEN: ttb3_O2cK_yYZg_pFkl
