apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-cra
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: hello-cra
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/sikalabs/charts.git
    targetRevision: HEAD
    path: charts/hello-world
    helm:
      releaseName: hello-world
      values: |
        host: hello-cra.k8s.sikademo.com
        image: sikalabs/hello-world-server:cra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
