apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-heidelberg
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: hello-heidelberg
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  source:
    repoURL: https://github.com/sikalabs/charts.git
    targetRevision: HEAD
    path: charts/hello-world
    helm:
      releaseName: hello-heidelberg
      values: |
        host: hello-heidelberg.k8s.sikademo.com
        image: sikalabs/hello-world-server:heidelbergmaterials
