apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iceland-4
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/sikalabs/charts.git
    path: charts/one-image
    helm:
      valuesObject:
        host: ice-4.k8s.sikademo.com
        image: ondrejsika/iceland-4
