apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iceland-3
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://helm.sikalabs.io
    chart: one-image
    targetRevision: 1.17.0
    helm:
      valuesObject:
        host: ice-3.k8s.sikademo.com
        image: ondrejsika/iceland-3
