apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: rabbitmq
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 11.9.3
    chart: rabbitmq
    helm:
      releaseName: rabbitmq
      values: |
        auth:
          username: admin
          password: admin
        replicaCount: 3
        ingress:
          enabled: true
          ingressClassName: nginx
          hostname: rabbitmq.k8s.sikademo.com
          # TLS
          tls: true
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
