apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-secrets-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: vault-secrets-operator
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault-secrets-operator
    targetRevision: 0.2.0
    helm:
      releaseName: vault-secrets-operator
      values: |
       defaultVaultConnection:
        enabled: true
        address: "https://vault.k8s.sikademo.com"
        skipTLSVerify: false
        spec:
        template:
          spec:
            containers:
            - name: manager
              args:
              - "--client-cache-persistence-model=direct-encrypted"
