apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.csv: |
    g, argocd-admin, role:admin
    g, argocd-readonly, role:readonly
  policy.default: ""
  scopes: '[groups]'
