apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  scopes: '[groups]'
  policy.default: ""
  policy.csv: |
    g, argocd-admin, role:admin
    g, argocd-readonly, role:readonly
    g, argocd-foo, role:foo

    p, role:foo, projects, get, foo/*, allow
    p, role:foo, applications, get, foo/*, allow

    p, role:foo, Pod, delete, foo/*, allow
    p, role:foo, exec, create, foo/*, allow
