apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: hello
  annotations:
    kargo.akuity.io/color: "#F44336"
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: hello
      sources:
        stages:
          - stage
  promotionTemplate:
    spec:
      steps:
        - uses: git-clone
          config:
            repoURL: git@github.com:ondrejsikax/kcd2026-kargo-test.git
            checkout:
              - branch: master
                path: ./repo
        - uses: yaml-update
          config:
            path: ./repo/clusters/kargo2/hello/values/prod/env.values.yaml
            updates:
              - key: image
                value: ${{ imageFrom("ttl.sh/ondrejsikax/kcd2026-kargo-test").RepoURL + ":" + imageFrom("ttl.sh/ondrejsikax/kcd2026-kargo-test").Tag }}
        - uses: copy
          config:
            inPath: ./repo/clusters/kargo2/hello/values/stage/common.values.yaml
            outPath: ./repo/clusters/kargo2/hello/values/prod/common.values.yaml
        - uses: git-commit
          config:
            path: ./repo
            message: 'chore(clusters/kargo2/hello/values): promote hello:${{ imageFrom("ttl.sh/ondrejsikax/kcd2026-kargo-test").Tag }} image to prod'
            author:
              name: SikaLabs[bot]
              email: sikalabsbot@sikalabs.com
        - uses: copy
          config:
            inPath: ./repo/clusters/kargo2/hello/values/stage/common.values.yaml
            outPath: ./repo/clusters/kargo2/hello/values/prod/common.values.yaml
        - uses: git-commit
          config:
            path: ./repo
            message: 'chore(clusters/kargo2/hello/values): promote hello values to prod'
            author:
              name: SikaLabs[bot]
              email: sikalabsbot@sikalabs.com
        - uses: git-push
          config:
            path: ./repo
        - uses: argocd-update
          config:
            apps:
              - name: hello-prod
