apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: 1.16.3
    helm:
      valuesObject:
        crds:
          enabled: true
          keep: true
        extraObjects:
          - |
            apiVersion: cert-manager.io/v1
            kind: ClusterIssuer
            metadata:
              name: letsencrypt
            spec:
              acme:
                email: ondrejsika@ondrejsika.com
                server: https://acme-v02.api.letsencrypt.org/directory
                privateKeySecretRef:
                  name: letsencrypt-issuer-account-key
                solvers:
                  - http01:
                      ingress:
                        class: nginx
