apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-a
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: a
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://helm.sikademo.com
    chart: gordy-redis
    targetRevision: 0.1.0
    helm:
      valuesObject:
        appendonly: "no"
