apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: generali-counter
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: generali-counter
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: hhttps://github.com/sika-training-examples/2025-06-20_generali_example_helm
    path: .
    helm:
      valuesObject:
        frontend:
          host: generali-counter.openshift.sikademo.com
