apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-generali
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: hello-generali
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/sikalabs/charts.git
    path: charts/hello-world
    helm:
      valuesObject:
        host: hello-generali.openshift.sikademo.com
        image: ghcr.io/sikalabs/hello-world-server:generali
        replicas: 3

