apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: counter-from-manifests
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: counter-from-manifests
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/sika-training-examples/2024-04-10-counter-manifests-example.git
    path: .
