apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: counter-from-helm
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: counter-from-helm
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/sika-training-examples/2024-04-12-counter-helm.git
    path: .
    helm:
      valuesObject:
        host: counter-from-helm.cro.sikademo.com
