apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example
  namespace: cra-argocd
spec:
  destination:
    namespace: example
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/sikalabs/charts.git
    targetRevision: HEAD
    path: charts/hello-world
    helm:
      releaseName: example
      values: |
        host: cra.sikademo.com
        image: sikalabs/hello-world-server:cra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
