apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: counter
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: counter
  destination:
    namespace: counter
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    path: .
    repoURL: https://github.com/sika-training-examples/2025-10-06-counter-manifests.git
