apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: stage
  namespace: counter
  annotations:
    kargo.akuity.io/color: "#FFEB3B"
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: counter
      sources:
        stages:
          - dev
  promotionTemplate:
    spec:
      steps:
        - uses: git-clone
          config:
            repoURL: git@github.com:ondrejsikax/kcd2026-kargo-test.git
            checkout:
              - branch: master
                path: ./repo
        - uses: yaml-update
          config:
            path: ./repo/clusters/kargo2/counter/values/stage/env.values.yaml
            updates:
              - key: backendImage
                value: ${{ imageFrom("ttl.sh/ondrejsikax/kcd2026-kargo-test/backend").RepoURL + ":" + imageFrom("ttl.sh/ondrejsikax/kcd2026-kargo-test/backend").Tag }}
              - key: frontendImage
                value: ${{ imageFrom("ttl.sh/ondrejsikax/kcd2026-kargo-test/frontend").RepoURL + ":" + imageFrom("ttl.sh/ondrejsikax/kcd2026-kargo-test/frontend").Tag }}
        - uses: git-commit
          config:
            path: ./repo
            message: 'chore(clusters/kargo2/counter/values): promote counter backend:${{ imageFrom("ttl.sh/ondrejsikax/kcd2026-kargo-test/backend").Tag }} frontend:${{ imageFrom("ttl.sh/ondrejsikax/kcd2026-kargo-test/frontend").Tag }} image to stage'
            author:
              name: SikaLabs[bot]
              email: sikalabsbot@sikalabs.com
        - uses: copy
          config:
            inPath: ./repo/clusters/kargo2/counter/values/dev/common.values.yaml
            outPath: ./repo/clusters/kargo2/counter/values/stage/common.values.yaml
        - uses: git-commit
          config:
            path: ./repo
            message: 'chore(clusters/kargo2/counter/values): promote counter values to stage'
            author:
              name: SikaLabs[bot]
              email: sikalabsbot@sikalabs.com
        - uses: git-push
          config:
            path: ./repo
        - uses: argocd-update
          config:
            apps:
              - name: counter-stage
