apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: public-example
  namespace: argocd
spec:
  destination:
    namespace: public-www
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/sikalabs/charts.git
    targetRevision: HEAD
    path: charts/hello-world
    helm:
      releaseName: hello-world
      values: |
        host: public-hello-world.joh.k8s.sl.zone
        image: sikalabs/hello-world-server:ondrejsika
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
