apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: www-hello-o2
  namespace: argocd
spec:
  destination:
    namespace: www
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/sikalabs/charts.git
    targetRevision: HEAD
    path: charts/hello-world
    helm:
      releaseName: hello-o2
      values: |
        host: hello-o2.joh.k8s.sl.zone
        image: sikalabs/hello-world-server:o2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
