apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-pickey
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: example
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/sikalabs/charts.git
    targetRevision: HEAD
    path: charts/hello-world
    helm:
      releaseName: hello-pickey
      values: |
        host: hello-pickey.joh.k8s.sl.zone
        TEXT: Hello Pickey!
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
