apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ceps-cz
  namespace: openshift-operators
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: openshift-operators
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/sika-training-examples/2023-11-03-ceps-cz-website-example.git
    targetRevision: HEAD
    path: ./charts/ceps-cz
    helm:
      releaseName: ceps-cz
      values: |
        host: ceps-cz.apps.okd.aws.sikademo.com
        replicas: 12
