apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: counter-from-git
  namespace: openshift-operators
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: openshift-operators
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/sika-training-examples/2023-11-03_ceps_counter_helm_example.git
    targetRevision: HEAD
    path: .
    helm:
      releaseName: counter-from-git
      values: |
        host: counter-from-git.apps.okd.aws.sikademo.com
        counterReplicas: 2
