apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: counter-from-helm
  namespace: openshift-operators
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: openshift-operators
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://helm.sikademo.com
    targetRevision: 2023.11.02
    chart: counter
    helm:
      releaseName: counter-from-helm
      values: |
        host: counter-from-helm.apps.okd.aws.sikademo.com
        counterReplicas: 4

