apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: counter-manifest
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: counter-manifest
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/sika-training-examples/2025-10-06-counter-manifests.git
    path: .
