apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: kafka-bar
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka
spec:
  topicName: bar
  partitions: 27
  replicas: 3
  config:
    retention.bytes: 536870912 # 512Mi per partition
