apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: kafka-openshift-logs
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka
spec:
  topicName: openshift-logs
  partitions: 27
  replicas: 3
  config:
    retention.bytes: 536870912 # 512Mi per partition
