configs:
  cm:
    url: https://argocd.k8s.sikademo.com
    exec.enabled: "true"
    oidc.config: |
      name: SSO
      issuer: https://sso.sikalabs.com/realms/training
      clientID: example_client_id
      clientSecret: example_client_secret
      requestedScopes: ["openid", "profile", "email", "groups"]
      logoutURL: "https://sso.sikalabs.com/realms/training/protocol/openid-connect/logout?client_id=example_client_id&id_token_hint={{token}}&post_logout_redirect_uri=https://argocd.k8s.sikademo.com"
  rbac:
    scopes: '[groups]'
    policy.default: ""
    policy.csv: |
      g, argocd-admin, role:admin

      g, argocd-plzen, role:argocd-plzen
      p, role:argocd-plzen, projects, get, plzen/*, allow
      p, role:argocd-plzen, applications, get, plzen/*, allow
      p, role:argocd-plzen, applications, action/apps/Deployment/restart, plzen/*, allow
      p, role:argocd-plzen, applications, sync, plzen/*, allow
      p, role:argocd-plzen, applications, update, plzen/*, allow
      p, role:argocd-plzen, logs, get, plzen/*, allow
      p, role:argocd-plzen, exec, create, plzen/*, allow
server:
  ingress:
    enabled: true
    hostname: argocd.k8s.sikademo.com
    tls: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
