apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-cleevio
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: hello-cleevio
  destination:
    namespace: hello-cleevio
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://github.com/sikalabs/charts.git
      path: charts/hello-world
      helm:
        valueFiles:
          - $values/clusters/cleevio/hello_cleevio/hello_cleevio.values.yml
    - repoURL: https://github.com/ondrejsika/argocd-apps-public.git
      ref: values
