apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-counter-frontend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: examples
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/ondrejsika/counter-frontend.git
    path: kubernetes/chart
    helm:
      releaseName: counter-frontend
      valuesObject:
        host: counter-frontend.sikademo.com
        API_ORIGIN: http://counter-backend-counter
        FONT_COLOR: "#ffffff"
        BACKGROUND_COLOR: "#131480"
