apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-from-git-repo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: examples
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://github.com/sikalabs/charts.git
    targetRevision: HEAD
    path: charts/hello-world
    helm:
      releaseName: example-from-git-repo
      valuesObject:
        host: example-from-git-repo.panda.k8s.sl.zone
        image: sikalabs/hello-world-server:v0.6.0
        TEXT: "Example from Git repo"
        COLOR: "white"
        BACKGROUND_COLOR: "black"
