apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: artifactory
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: artifactory
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://charts.jfrog.io
    chart: artifactory
    targetRevision: 107.98.9
    helm:
      valuesObject:
        # https://artifacthub.io/packages/helm/jfrog/artifactory?modal=values
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx
            cert-manager.io/cluster-issuer: letsencrypt
            nginx.ingress.kubernetes.io/proxy-body-size: "500m"
          hosts:
            - artifactory.sikademo.com
          tls:
            - hosts:
                - artifactory.sikademo.com
              secretName: artifactory.sikademo.com-tls
