apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-iceland-4
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: examples
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  source:
    repoURL: https://github.com/sikalabs/charts.git
    targetRevision: HEAD
    path: charts/one-image
    helm:
      releaseName: example-iceland-4
      valuesObject:
        host: example-iceland-4.k8s.sikademo.com
        image: ghcr.io/ondrejsika/iceland-4
