apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: signpost
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: signpost
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  sources:
    - repoURL: https://github.com/sikalabs/charts.git
      path: charts/signpost
      helm:
        valueFiles:
          - $values/apps/openshift/signpost/signpost.values.yaml
    - repoURL: https://github.com/ondrejsika/argocd-apps-public.git
      ref: values
