apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- all.yml

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: hello-world-kustomized
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
