apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: loki
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 5.48.0
    helm:
      valuesObject:
        minio:
          enabled: false

        loki:
          auth_enabled: false
          server:
            http_server_write_timeout: 310s
            http_server_read_timeout: 310s
            grpc_server_max_recv_msg_size: 104857600  # 100 Mb
            grpc_server_max_send_msg_size: 104857600  # 100 Mb
          ingester:
            chunk_encoding: snappy
            chunk_idle_period: 2h
            chunk_target_size: 1536000 # 1.5 Mb
            max_chunk_age: 2h
          limits_config:
            max_query_parallelism: 24
            ingestion_rate_mb: 20
            ingestion_burst_size_mb: 30
            per_stream_rate_limit: "3MB"
            per_stream_rate_limit_burst: "10MB"
            query_timeout: 300s
            max_query_series: 5000
            max_entries_limit_per_query: 200000
            retention_period: 48h
            retention_stream:
              - selector: '{namespace="monitoring"}'
                priority: 100
                period: 72h
          compactor:
            working_directory: /var/loki/retention
            compaction_interval: 10m
            retention_enabled: true
            retention_delete_delay: 2h
            retention_delete_worker_count: 150
            shared_store: s3
          query_scheduler:
            max_outstanding_requests_per_tenant: 2048
            grpc_client_config:
              max_recv_msg_size: 104857600  # 100 Mb
              max_send_msg_size: 104857600  # 100 Mb
          query_range:
            parallelise_shardable_queries: false
            align_queries_with_step: true
            max_retries: 5
            cache_results: true
          querier:
            max_concurrent: 16
            engine:
              timeout: 300s
          frontend_worker:
            match_max_concurrent: true
          commonConfig:
            replication_factor: 1
          storage:
            bucketNames:
              chunks: loki-chunks
              ruler: loki-ruler
              admin: loki-admin
            type: 's3'
            s3:
              endpoint: http://minio.minio:9000
              accessKeyId: admin
              secretAccessKey: asdfasdf
              s3ForcePathStyle: true
              insecure: false
          storage_config:
            boltdb_shipper:
              active_index_directory: /var/loki/index
              cache_location: /var/loki/cache
              shared_store: s3

        backend:
          replicas: 2
          persistence:
            size: 1Gi

        read:
          replicas: 2
          persistence:
            size: 1Gi

        write:
          replicas: 2
          persistence:
            size: 2Gi

        gateway:
          replicas: 2
          ingress:
            enabled: true
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt
            hosts:
              - host: loki.k8s-us.sikademo.com
                paths:
                  - path: /
                    pathType: Prefix
            tls:
              - secretName: loki.k8s-us.sikademo.com-tls
                hosts:
                  - loki.k8s-us.sikademo.com
