apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: minio
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  source:
    repoURL: https://charts.min.io/
    chart: minio
    targetRevision: 5.2.0
    helm:
      valuesObject:
        rootUser: admin
        rootPassword: asdfasdf

        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt
          hosts:
            - minio.k8s-us.sikademo.com
          tls:
           - secretName: minio.k8s-us.sikademo.com-tls
             hosts:
               - minio.k8s-us.sikademo.com

        consoleIngress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt
          hosts:
            - minio-console.k8s-us.sikademo.com
          tls:
           - secretName: minio-console.k8s-us.sikademo.com-tls
             hosts:
               - minio-console.k8s-us.sikademo.com

        buckets:
          - name: loki-chunks
            policy: none
            purge: false
          - name: loki-ruler
            policy: none
            purge: false
          - name: loki-admin
            policy: none
            purge: false

        replicas: 2
        drivesPerNode: 1

        persistence:
          enabled: true
          # storageClass: longhorn
          size: 15Gi

        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 1500Mi
