apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-prom
  namespace: cra-argocd
spec:
  destination:
    namespace: cra-prom
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 19.3.0
    helm:
      releaseName: prom
      # https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml

      values: |
        alertmanager:
          enabled: false

        grafana:
          enabled: false

        defaultRules:
          rules:
            alertmanager: false

        kubeControllerManager:
          enabled: false

        kubeDns:
          enabled: false

        kubeEtcd:
          enabled: false

        kubeScheduler:
          enabled: false

        kubeProxy:
          enabled: false

        prometheus-node-exporter:
          service:
            port: 32100
            targetPort: 32100

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
