apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  name: loki
  namespace: openshift-machine-api
spec:
  replicas: 2
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: training-85hnr
      machine.openshift.io/cluster-api-machineset: loki
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: training-85hnr
        machine.openshift.io/cluster-api-machine-role: worker
        machine.openshift.io/cluster-api-machine-type: worker
        machine.openshift.io/cluster-api-machineset: loki
    spec:
      lifecycleHooks: {}
      metadata: {}
      providerSpec:
        value:
          acceleratedNetworking: true
          apiVersion: machine.openshift.io/v1beta1
          credentialsSecret:
            name: azure-cloud-credentials
            namespace: openshift-machine-api
          diagnostics:
            boot:
              storageAccountType: AzureManaged
          image:
            offer: aro4
            publisher: azureopenshift
            resourceID: ""
            sku: aro_419
            type: MarketplaceNoPlan
            version: 419.6.20250523
          kind: AzureMachineProviderSpec
          location: germanywestcentral
          metadata:
            creationTimestamp: null
          networkResourceGroup: egd
          osDisk:
            diskSettings: {}
            diskSizeGB: 128
            managedDisk:
              securityProfile:
                diskEncryptionSet: {}
              storageAccountType: Premium_LRS
            osType: Linux
          publicIP: false
          publicLoadBalancer: training-85hnr
          resourceGroup: aro-infra-mm3xjbpn-training
          securityProfile:
            settings: {}
          subnet: worker-subnet
          userDataSecret:
            name: worker-user-data
          vmSize: Standard_D8s_v5
          vnet: aro-vnet-mm3xj3bw
          zone: "1"
