apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki-operator
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-90"
spec:
  project: system
  destination:
    namespace: openshift-operators-redhat
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: https://github.com/ondrejsika/argocd-apps-public.git
      path: ./clusters/openshift_training/_system/loki_operator/manifests
