apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: grafana
  destination:
    namespace: grafana
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  sources:
  - repoURL: https://gitlab.sikalabs.com/examples/pss/pss-charts.git
    path: charts/pss-app
    helm:
      valueFiles:
      - '$values/apps/pss/grafana/grafana.values.yaml'
  - repoURL:  https://gitlab.sikalabs.com/examples/pss/pss-argocd-apps.git
    ref: values
